#!/usr/bin/env bash
# A Bash script that prints information about domains and/or subdomains
# Usage: ./0-world_wide_web <domain> OR ./0-world_wide_web <domain> <subdomain>

about_domain () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  about_domain "$1" "www"
  about_domain "$1" "lb-01"
  about_domain "$1" "web-01"
  about_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  about_domain "$1" "$2"
fi
