#!/usr/bin/env bash
# A Bash script that configures an Nginx server
#  so that /redirect_me redirects to another page.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'ALX Software Engineering' > /var/www/html/index.nginx-debian.html

REDIRECT=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

bash -c "echo -e '$REDIRECT' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
