#!/usr/bin/env bash
# A Bash script that configures an Nginx server with a custom 404 page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'ALX Software Engineering' > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
