#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Create MySQL dump, backup.sql:
mysqldump -u root --password="$1" --all-databases > backup.sql

# Set name format for the archive:
name=$(date +"%d")-$(date +"%m")-$(date +"%Y")

# Create archive:
tar -cz --file=$name.tar.gz backup.sql
