#!/usr/bin/env bash
# A Bash script that configures Nginx to listen on port 80 on all IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
