#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes.
#  Shows all processes, for all users, including those which might not have a TTY
#  Displays in a user-oriented format and shows process hierarchy

ps -auxf