#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely.
# Adds a sleep 2 in between each iteration of the loop.

while true
do
    echo "To infinity and beyond"
    sleep 2
done