#!/usr/bin/env bash
# A Bash script that indefinitely writes I am alive! to the file
#   /tmp/my_process after every 2-second pause
while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
