#!/usr/bin/env bash
#  A Bash script that displays numbers from 1 to 100.
#  Displays FizzBuzz when the number is a multiple of 3 and 5
#  Requirements:
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#    In a list format

for (( fb=1; fb<=100; fb++))
do
    if (( fb % 3 == 0 && fb % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( fb % 3 == 0 ))
    then
        echo "Fizz"
    elif (( fb % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$fb"
    fi
done
