#!/usr/bin/env bash
#  A Bash script that displays the visitor IP along with the HTTP status code
#+ from the Apache log file using awk in the format: IP HTTP_CODE.

awk '{print $1 " " $9}' apache-access.log
