#!/usr/bin/env bash
#  A Bash script that groups visitors by IP and HTTP status code, and displays this data in the format OCCURENCE_NUMBER IP HTTP_CODE using awk.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
