#!/usr/bin/env bash
#  A Bash script that loops from 1 to 10 and:
#+	displays bad luck for the 4th loop iteration
#+	displays good luck for the 8th loop iteration
#+	displays Best School for the other iterations
#  Uses a while loop and if, elif and else statements.

idx=0

while [ $idx -lt 10 ]
do
	if [ $idx -eq 3 ]
	then
		echo "bad luck"
	elif [ $idx -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"	
	fi
	(( idx++ ))
done
