#!/usr/bin/env bash
#  A Bash script that displays numbers from 1 to 20 and:
#	displays 4 and then bad luck from China for the 4th loop iteration
#+	displays 9 and then bad luck from Japan for the 9th loop iteration
#+	displays 17 and then bad luck from Italy for the 17th loop iteration
#  Uses a while loop and a case statement.

idx=1

while [ $idx -lt 21 ] 
do
	echo "$idx"
	case $idx in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	(( idx++ ))
done
