#!/usr/bin/env bash
#  A Bash script that displays the time for 12 hours and 59 minutes:
#+	display hours from 0 to 12
#+	display minutes from 1 to 59 
#  Uses the while loop

hr=0

while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	min=0
	while [ $min -lt 60 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hr++ ))
done
