#!/usr/bin/env bash
#  A Bash script that displays:
#	the content of the current directory
#	in a list format
#	where only the part of the name after the first dash is displayed
#+	(refer to the example)
#  Uses a for loop and hidden files are not displayed.

LIST=$(ls)

for i in $LIST;
do
	echo "$i" | cut -d '-' -f2
done
