#!/usr/bin/env bash
# Bash script that configures an Ubuntu server to make: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
cp ~/hosts ~/hosts.old
echo "127.0.0.2 localhost" > ~/hosts
echo "8.8.8.8   facebook.com" >> ~/hosts
cp -f ~/hosts.old ~/hosts
