#!/usr/bin/env bash
# Bash script that configures an Ubuntu server to make: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.ed
echo "127.0.0.2 localhost" > ~/hosts.ed
echo "8.8.8.8   facebook.com" >> ~/hosts.ed
cp -f ~/hosts.ed /etc/hosts
